service: video-moderation-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:Query"
      Resource:
        - "Fn::Join":
            [
              "",
              [
                "arn:aws:dynamodb:",
                { "Ref": "AWS::Region" },
                ":",
                { "Ref": "AWS::AccountId" },
                ":table/${file(config.json):DYNAMODB_TABLE}",
              ],
            ]

functions:
  createRoom:
    handler: api/room.handler
    events:
      - http:
          path: /room
          method: post
          cors: true
    environment:
      OPENTOK_API_KEY: ${file(config.json):OPENTOK_API_KEY}
      OPENTOK_API_SECRET: ${file(config.json):OPENTOK_API_SECRET}      


resources:
  Resources:
    VideoModerationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TableName: ${file(config.json):DYNAMODB_TABLE}
